### ISSUE TITLE
Lack of library imports: traceback and platform

### ISSUE THREAD

**Issue by YukiYasuda2718** [clstoulouse/motu-client-python#24]
Hello.

I found a bug of lack of two library imports (`traceback` and `platform`)  in `src/python/motu_utils/motu_api.py` when my internet connection was lost. I am reporting here because I am not sure if the codes work correctly by just adding these imports. I would appreciate it if you gave some comments to me.

### My environment

- macOS: 10.15.7
- Python: 3.7.4
- motuclient: 1.8.6

### How to reproduce the bag

- After the connection is established and before the download is finished, disconnect to the Internet
- The following are error messages

```
Download failed: timed out
Traceback (most recent call last):
  File "/Users/yyuuki/opt/anaconda3/lib/python3.7/site-packages/motu_utils/motu_api.py", line 419, in dl_2_file
    read = utils_stream.copy(m, temp, progress_function if size != -1 else none_function, block_size)
  File "/Users/yyuuki/opt/anaconda3/lib/python3.7/site-packages/motu_utils/utils_stream.py", line 43, in copy
    block = sourceHandler.read(blockSize)
  File "/Users/yyuuki/opt/anaconda3/lib/python3.7/http/client.py", line 470, in read
    s = self._safe_read(self.length)
  File "/Users/yyuuki/opt/anaconda3/lib/python3.7/http/client.py", line 620, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/Users/yyuuki/opt/anaconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample.py", line 50, in <module>
    motuclient.motu_api.execute_request(MotuOptions(opt))
  File "/Users/yyuuki/opt/anaconda3/lib/python3.7/site-packages/motu_utils/motu_api.py", line 661, in execute_request
    dl_2_file(dwurl, fh, _options.block_size, not (_options.describe or _options.size), **url_config)
  File "/Users/yyuuki/opt/anaconda3/lib/python3.7/site-packages/motu_utils/motu_api.py", line 454, in dl_2_file
    x = traceback.format_exception(exc_type, exc_value, exc_tb)
NameError: name 'traceback' is not defined
```

### Codes to reproduce the bag

```
import motuclient

cmems_usr = "XXXXX"
cmems_passwd = "YYYYY"


class MotuOptions:
    def __init__(self, attrs: dict):
        super(MotuOptions, self).__setattr__("attrs", attrs)

    def __setattr__(self, k, v):
        self.attrs[k] = v

    def __getattr__(self, k):
        try:
            return self.attrs[k]
        except KeyError:
            return None


opt = {
    "service_id": "GLOBAL_ANALYSIS_FORECAST_PHY_001_024-TDS",
    "product_id": "global-analysis-forecast-phy-001-024-hourly-t-u-v-ssh",
    "date_min": "2021-01-06 12:00:00",
    "date_max": "2021-01-06 13:00:00",
    "longitude_min": -180,
    "longitude_max": 180,
    "latitude_min": -90,
    "latitude_max": 90,
    "depth_min": 0.494024,
    "depth_max": 0.494026,
    "variable": ["thetao"],
    "socket_timeout": 1.0,
    "motu": "http://nrt.cmems-du.eu/motu-web/Motu",
    "out_dir": ".",
    "out_name": "output.nc",
    "auth_mode": "cas",
    "user": cmems_usr,
    "pwd": cmems_passwd,
}

motuclient.motu_api.execute_request(MotuOptions(opt))
```

**Comment by clstoulouse** [comment]
Hi,

Thank you for reporting this issue, we have well  reproduced your issue and we will fix it in the coming days. We will notify you once the release fixing this issue will be available on GitHub.

Regards,
CLS Motu team

**Comment by YukiYasuda2718** [comment]
Thank you very much for investigating and fixing this issue!!

**Comment by clstoulouse** [comment]
Hi,

We have released a new version of the motu-client-python which fixes your issue.
https://github.com/clstoulouse/motu-client-python/releases/tag/motuclient-python-1.8.7

Let us know if you find any other issues.

Best regards and have fun with Motu,
Motu Dev team

**Comment by YukiYasuda2718** [comment]
I have checked the new version. Thank you very much for the quick response!
